import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import type { ContractTerms, DealKind, Partner, Project, QuoteItem } from '../types';
import { CURRENT_USER, TERMS_TEMPLATES } from '../data/sampleData';
import { calcTotals, lineAmount } from '../utils/calc';
import { buildComplianceItems, complianceSummary } from '../utils/docs';
import { addDays, formatYen, nowIso, todayIso } from '../utils/format';
import { EmptyState } from '../components/EmptyState';

interface Props {
  partners: Partner[];
  projects: Project[];
  onCreate: (project: Project) => void;
  newId: () => string;
  onToast: (message: string, type?: 'success' | 'info' | 'error') => void;
}

const STAFF_OPTIONS = ['中村 遥', '藤代 悠斗', '小柳 里菜'];

const STEPS = ['基本情報', '見積明細', '契約条件・確認'];

const DEFAULT_TERMS: ContractTerms = {
  startDate: '',
  endDate: '',
  nonWorkingDays: '日曜日および年末年始（12/29〜1/3）は施工しない',
  advancePayment: '',
  inspection: '完成通知の受領後14日以内に発注者立会いのもと完成検査を行う',
  handover: '完成検査合格後7日以内に引渡しを行う',
  paymentMethod: '',
  defectLiability: '引渡しの日から2年間（設備機器は1年間）',
  delayPenalty: '年率3.0％の遅延利息を付す',
  thirdPartyDamage: '施工に起因して第三者に与えた損害は受注者が負担する（不可抗力による場合を除く）',
  suppliedMaterials: '支給材料・貸与機械なし',
  disputeResolution: '協議のうえ解決し、協議が調わない場合は建設工事紛争審査会のあっせん・調停による',
  termsTemplateId: 'tpl-standard',
};

function nextProjectNo(projects: Project[]): string {
  const max = projects.reduce((acc, p) => {
    const n = Number(p.no.split('-').pop());
    return Number.isNaN(n) ? acc : Math.max(acc, n);
  }, 0);
  return `KJ-2026-${String(max + 1).padStart(4, '0')}`;
}

export function ProjectNew({ partners, projects, onCreate, newId, onToast }: Props) {
  const navigate = useNavigate();
  const [step, setStep] = useState(0);
  const [dealKind, setDealKind] = useState<DealKind>('receive');
  const [partnerId, setPartnerId] = useState('');
  const [title, setTitle] = useState('');
  const [site, setSite] = useState('');
  const [scope, setScope] = useState('');
  const [staff, setStaff] = useState(CURRENT_USER.name);
  const [quotedOn, setQuotedOn] = useState(todayIso());
  const [quoteExpiry, setQuoteExpiry] = useState(addDays(30));
  const [items, setItems] = useState<QuoteItem[]>([
    { id: 'new-1', name: '', spec: '', quantity: 1, unit: '式', unitPrice: 0 },
  ]);
  const [discount, setDiscount] = useState(0);
  const [terms, setTerms] = useState<ContractTerms>(DEFAULT_TERMS);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const projectNo = useMemo(() => nextProjectNo(projects), [projects]);
  const seqNo = projectNo.split('-').pop() ?? '0000';

  const selectablePartners = partners.filter(p => (dealKind === 'receive' ? p.kind === 'client' : p.kind === 'subcontractor'));
  const partner = partners.find(p => p.id === partnerId);
  const totals = calcTotals(items, discount);

  /** 入力内容からプレビュー用・登録用の案件データを組み立てる */
  const buildProject = (id: string): Project => ({
    id,
    no: projectNo,
    title: title.trim(),
    dealKind,
    status: 'draft',
    partnerId,
    site: site.trim(),
    scope: scope.trim(),
    staff,
    quotedOn,
    quoteExpiry,
    items: items.map((it, i) => ({ ...it, id: `it-${seqNo}-${i + 1}` })),
    discount,
    terms,
    documents: [
      { kind: 'quote', no: `EST-2026-${seqNo}`, status: 'created', issuedOn: quotedOn, autoGenerated: false },
      { kind: 'order', no: '', status: 'none', autoGenerated: false },
      { kind: 'acceptance', no: '', status: 'none', autoGenerated: false },
      { kind: 'terms', no: '', status: 'none', autoGenerated: false },
    ],
    revision: 1,
    history: [
      {
        id: `hx-${seqNo}-1`,
        at: nowIso(),
        actorName: CURRENT_USER.name,
        action: `見積書 EST-2026-${seqNo} を作成しました`,
      },
    ],
    updatedAt: nowIso(),
  });

  const compliance = useMemo(() => {
    if (!partner) return null;
    return complianceSummary(buildComplianceItems(buildProject('preview'), partner));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [partner, title, site, scope, items, discount, terms, dealKind]);

  const validateStep1 = () => {
    const e: Record<string, string> = {};
    if (!partnerId) e.partnerId = dealKind === 'receive' ? '発注者（得意先）を選択してください' : '協力会社を選択してください';
    if (!title.trim()) e.title = '工事名称を入力してください';
    if (!site.trim()) e.site = '工事場所を入力してください';
    if (!scope.trim()) e.scope = '工事内容を入力してください';
    if (quoteExpiry < quotedOn) e.quoteExpiry = '見積有効期限は見積提出日以降の日付にしてください';
    setErrors(e);
    return Object.keys(e).length === 0;
  };

  const validateStep2 = () => {
    const e: Record<string, string> = {};
    const valid = items.filter(it => it.name.trim() && it.quantity > 0 && it.unitPrice > 0);
    if (valid.length === 0) e.items = '工種・品名、数量、単価を入力した明細を1行以上登録してください';
    if (discount > totals.subtotal) e.discount = '値引額は小計を超えないようにしてください';
    setErrors(e);
    return Object.keys(e).length === 0;
  };

  const goNext = () => {
    if (step === 0 && !validateStep1()) {
      onToast('未入力の項目があります。赤字の項目をご確認ください', 'error');
      return;
    }
    if (step === 1) {
      if (!validateStep2()) {
        onToast('見積明細に不備があります。内容をご確認ください', 'error');
        return;
      }
      setItems(items.filter(it => it.name.trim()));
    }
    setErrors({});
    setStep(step + 1);
  };

  const submit = () => {
    if (!validateStep1() || !validateStep2()) {
      onToast('入力内容に不備があります。前のステップをご確認ください', 'error');
      setStep(0);
      return;
    }
    const project = buildProject(newId());
    onCreate(project);
    navigate(`/project/${project.id}`);
  };

  const updateItem = (id: string, patch: Partial<QuoteItem>) => {
    setItems(prev => prev.map(it => (it.id === id ? { ...it, ...patch } : it)));
  };

  return (
    <>
      <div className="page-head">
        <div>
          <h1 className="page-title">新規見積の作成</h1>
          <div className="page-sub">
            案件番号 {projectNo}／見積書番号 EST-2026-{seqNo}&#12288;（入力した内容は注文書・注文請書・約款へ自動反映されます）
          </div>
        </div>
        <button className="btn btn-ghost" onClick={() => navigate('/')}>
          一覧に戻る
        </button>
      </div>

      <div className="steps">
        {STEPS.map((label, i) => (
          <span key={label} className={`step ${i === step ? 'active' : i < step ? 'done' : ''}`}>
            <span className="step-no">{i < step ? '✓' : i + 1}</span>
            {label}
          </span>
        ))}
      </div>

      {step === 0 && (
        <div className="card card-pad">
          <div className="section-title"><span className="bar" />基本情報</div>

          <div className="field">
            <span className="field-label">取引区分<span className="req">必須</span></span>
            <div className="row gap-10 wrap">
              {(['receive', 'order'] as DealKind[]).map(k => (
                <label
                  key={k}
                  className="row gap-8"
                  style={{
                    border: `1px solid ${dealKind === k ? 'var(--accent)' : 'var(--border-strong)'}`,
                    background: dealKind === k ? 'var(--accent-soft)' : 'var(--card)',
                    borderRadius: 'var(--radius-md)',
                    padding: '12px 16px',
                    cursor: 'pointer',
                    minHeight: '44px',
                  }}
                >
                  <input
                    type="radio"
                    name="dealKind"
                    checked={dealKind === k}
                    onChange={() => {
                      setDealKind(k);
                      setPartnerId('');
                      setTerms(t => ({ ...t, termsTemplateId: k === 'receive' ? 'tpl-standard' : 'tpl-subcon' }));
                    }}
                  />
                  <span className="fs-13 fw-600">
                    {k === 'receive' ? '受注案件（発注者から受注する工事）' : '発注案件（協力会社へ発注する工事）'}
                  </span>
                </label>
              ))}
            </div>
            <div className="field-hint">
              取引区分により、注文書・注文請書の甲乙（注文者・受注者）と適用する約款テンプレートが切り替わります。
            </div>
          </div>

          <div className="form-grid">
            <div className="field">
              <label className="field-label" htmlFor="partner">
                {dealKind === 'receive' ? '発注者（得意先）' : '協力会社（下請）'}<span className="req">必須</span>
              </label>
              <select
                id="partner"
                className={errors.partnerId ? 'select invalid' : 'select'}
                value={partnerId}
                onChange={e => setPartnerId(e.target.value)}
              >
                <option value="">選択してください</option>
                {selectablePartners.map(p => (
                  <option key={p.id} value={p.id}>{p.name}</option>
                ))}
              </select>
              {errors.partnerId && <span className="field-error">{errors.partnerId}</span>}
            </div>

            <div className="field">
              <label className="field-label" htmlFor="staff">社内担当者</label>
              <select id="staff" className="select" value={staff} onChange={e => setStaff(e.target.value)}>
                {STAFF_OPTIONS.map(s => (
                  <option key={s} value={s}>{s}</option>
                ))}
              </select>
            </div>
          </div>

          {partner && (
            <div className="alert alert-info mb-16">
              <span aria-hidden="true">↺</span>
              <div>
                <div className="fw-600">取引先マスタから自動反映しました</div>
                <div className="fs-12 mt-4">
                  {partner.name}／{partner.department} {partner.contactName} 様<br />
                  〒{partner.postalCode} {partner.address}／TEL {partner.tel}<br />
                  支払条件：{partner.paymentTerms}
                  {partner.kind === 'subcontractor' && (
                    <>
                      <br />
                      建設業許可：{partner.licenseNo || '未登録（取引先マスタで登録してください）'}
                    </>
                  )}
                </div>
              </div>
            </div>
          )}

          <div className="field">
            <label className="field-label" htmlFor="title">工事名称<span className="req">必須</span></label>
            <input
              id="title"
              className={errors.title ? 'input invalid' : 'input'}
              value={title}
              onChange={e => setTitle(e.target.value)}
            />
            {errors.title && <span className="field-error">{errors.title}</span>}
          </div>

          <div className="field">
            <label className="field-label" htmlFor="site">工事場所<span className="req">必須</span></label>
            <input
              id="site"
              className={errors.site ? 'input invalid' : 'input'}
              value={site}
              onChange={e => setSite(e.target.value)}
            />
            {errors.site && <span className="field-error">{errors.site}</span>}
          </div>

          <div className="field">
            <label className="field-label" htmlFor="scope">工事内容（建設業法第19条第1項第1号）<span className="req">必須</span></label>
            <textarea
              id="scope"
              className={errors.scope ? 'textarea invalid' : 'textarea'}
              value={scope}
              onChange={e => setScope(e.target.value)}
            />
            {errors.scope && <span className="field-error">{errors.scope}</span>}
          </div>

          <div className="form-grid">
            <div className="field">
              <label className="field-label" htmlFor="quotedOn">見積提出日</label>
              <input id="quotedOn" type="date" className="input" value={quotedOn} onChange={e => setQuotedOn(e.target.value)} />
            </div>
            <div className="field">
              <label className="field-label" htmlFor="expiry">見積有効期限</label>
              <input
                id="expiry"
                type="date"
                className={errors.quoteExpiry ? 'input invalid' : 'input'}
                value={quoteExpiry}
                onChange={e => setQuoteExpiry(e.target.value)}
              />
              {errors.quoteExpiry && <span className="field-error">{errors.quoteExpiry}</span>}
            </div>
          </div>
        </div>
      )}

      {step === 1 && (
        <div className="card card-pad">
          <div className="section-title"><span className="bar" />見積明細</div>
          <div className="fs-12 text-sub mb-12">
            数量・単価を入力すると金額・消費税・合計が即時に再計算されます。ここで確定した金額が請負代金の額として各書類に反映されます。
          </div>

          {errors.items && <div className="alert alert-error mb-12"><span aria-hidden="true">!</span><div>{errors.items}</div></div>}

          <div className="table-wrap mb-16">
            <table className="items">
              <thead>
                <tr>
                  <th style={{ minWidth: '180px' }}>工種・品名</th>
                  <th style={{ minWidth: '200px' }}>仕様・規格</th>
                  <th style={{ width: '92px' }}>数量</th>
                  <th style={{ width: '86px' }}>単位</th>
                  <th style={{ width: '120px' }}>単価</th>
                  <th style={{ width: '120px' }} className="num">金額</th>
                  <th style={{ width: '60px' }}>操作</th>
                </tr>
              </thead>
              <tbody>
                {items.map(item => (
                  <tr key={item.id}>
                    <td><input className="input" value={item.name} onChange={e => updateItem(item.id, { name: e.target.value })} aria-label="工種・品名" /></td>
                    <td><input className="input" value={item.spec} onChange={e => updateItem(item.id, { spec: e.target.value })} aria-label="仕様・規格" /></td>
                    <td><input className="input num" type="number" min={0} value={item.quantity} onChange={e => updateItem(item.id, { quantity: Number(e.target.value) })} aria-label="数量" /></td>
                    <td><input className="input" value={item.unit} onChange={e => updateItem(item.id, { unit: e.target.value })} aria-label="単位" /></td>
                    <td><input className="input num" type="number" min={0} step={100} value={item.unitPrice} onChange={e => updateItem(item.id, { unitPrice: Number(e.target.value) })} aria-label="単価" /></td>
                    <td className="num fw-600">{formatYen(lineAmount(item))}</td>
                    <td>
                      <button
                        className="btn btn-ghost btn-sm"
                        onClick={() => {
                          if (items.length === 1) {
                            onToast('明細は1行以上必要です', 'error');
                            return;
                          }
                          setItems(prev => prev.filter(it => it.id !== item.id));
                          onToast('明細を1行削除しました', 'info');
                        }}
                        aria-label={`${item.name || 'この行'}を削除`}
                      >
                        削除
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="row between wrap gap-16">
            <button
              className="btn btn-secondary"
              onClick={() => setItems(prev => [...prev, { id: `new-${prev.length + 1}-${Date.now()}`, name: '', spec: '', quantity: 1, unit: '式', unitPrice: 0 }])}
            >
              ＋ 明細行を追加
            </button>

            <div className="total-box">
              <div className="total-line"><span>小計</span><span className="num">{formatYen(totals.subtotal)}</span></div>
              <div className="total-line">
                <label htmlFor="discount">値引額</label>
                <input
                  id="discount"
                  type="number"
                  min={0}
                  step={1000}
                  className={errors.discount ? 'input invalid num' : 'input num'}
                  style={{ width: '140px' }}
                  value={discount}
                  onChange={e => setDiscount(Math.max(0, Number(e.target.value)))}
                />
              </div>
              <div className="total-line"><span>消費税（10%）</span><span className="num">{formatYen(totals.tax)}</span></div>
              <div className="total-line grand"><span>合計（税込）</span><span className="num">{formatYen(totals.total)}</span></div>
            </div>
          </div>
          {errors.discount && <span className="field-error">{errors.discount}</span>}
        </div>
      )}

      {step === 2 && (
        <>
          <div className="card card-pad mb-16">
            <div className="section-title"><span className="bar" />契約条件（建設業法第19条第1項の記載事項）</div>
            <div className="fs-12 text-sub mb-16">
              ここで入力した内容が注文書・注文請書・基本契約書（約款）にそのまま記載されます。未入力の項目は法令チェックで「不足」として検知されます。
            </div>

            {compliance && (
              <div className={compliance.ok === compliance.total ? 'alert alert-success mb-16' : 'alert alert-warning mb-16'}>
                <span aria-hidden="true">{compliance.ok === compliance.total ? '✓' : '!'}</span>
                <div>
                  <div className="fw-600">
                    法定記載事項 {compliance.ok} / {compliance.total} 項目を充足（{compliance.rate}%）
                  </div>
                  <div className="fs-12 mt-4">
                    {compliance.ok === compliance.total
                      ? 'この内容で登録すると、建設業法上必要な記載事項をすべて満たした書類一式を作成できます。'
                      : '未入力の項目があります。登録後に「法令チェック」タブから追加入力することもできます。'}
                  </div>
                </div>
              </div>
            )}

            <div className="form-grid">
              <div className="field">
                <label className="field-label" htmlFor="startDate">工事着手の時期（第3号）</label>
                <input id="startDate" type="date" className="input" value={terms.startDate} onChange={e => setTerms({ ...terms, startDate: e.target.value })} />
              </div>
              <div className="field">
                <label className="field-label" htmlFor="endDate">工事完成の時期（第3号）</label>
                <input id="endDate" type="date" className="input" value={terms.endDate} onChange={e => setTerms({ ...terms, endDate: e.target.value })} />
              </div>
            </div>

            <div className="field">
              <label className="field-label" htmlFor="nonWorking">工事を施工しない日または時間帯（第4号）</label>
              <input id="nonWorking" className="input" value={terms.nonWorkingDays} onChange={e => setTerms({ ...terms, nonWorkingDays: e.target.value })} />
            </div>

            <div className="field">
              <label className="field-label" htmlFor="advance">前金払・出来形払の定め（第5号）</label>
              <input
                id="advance"
                className="input"
                value={terms.advancePayment}
                onChange={e => setTerms({ ...terms, advancePayment: e.target.value })}
              />
              <div className="field-hint">
                行わない場合も明記が必要です。
                <button
                  className="btn btn-ghost btn-sm"
                  style={{ marginLeft: '6px' }}
                  onClick={() => setTerms({ ...terms, advancePayment: '前金払・出来形払は行わない' })}
                >
                  「行わない」を入力
                </button>
              </div>
            </div>

            <div className="field">
              <label className="field-label" htmlFor="payment">完成後の請負代金の支払時期・方法（第12号）</label>
              <input id="payment" className="input" value={terms.paymentMethod} onChange={e => setTerms({ ...terms, paymentMethod: e.target.value })} />
              {partner && (
                <div className="field-hint">
                  取引先マスタの支払条件：{partner.paymentTerms}
                  <button
                    className="btn btn-ghost btn-sm"
                    style={{ marginLeft: '8px' }}
                    onClick={() => setTerms({ ...terms, paymentMethod: `引渡し後、${partner.paymentTerms}` })}
                  >
                    支払条件を反映する
                  </button>
                </div>
              )}
            </div>

            <div className="form-grid">
              <div className="field">
                <label className="field-label" htmlFor="inspection">完成検査の時期・方法（第11号）</label>
                <input id="inspection" className="input" value={terms.inspection} onChange={e => setTerms({ ...terms, inspection: e.target.value })} />
              </div>
              <div className="field">
                <label className="field-label" htmlFor="handover">引渡しの時期（第11号）</label>
                <input id="handover" className="input" value={terms.handover} onChange={e => setTerms({ ...terms, handover: e.target.value })} />
              </div>
            </div>

            <div className="field">
              <label className="field-label" htmlFor="template">適用する約款テンプレート</label>
              <select id="template" className="select" value={terms.termsTemplateId} onChange={e => setTerms({ ...terms, termsTemplateId: e.target.value })}>
                {TERMS_TEMPLATES.map(t => (
                  <option key={t.id} value={t.id}>{t.name}（{t.target}）</option>
                ))}
              </select>
              <div className="field-hint">
                設計変更・不可抗力・価格変動に関する条項（第6〜8号）はテンプレートから自動で付帯します。その他の条項は登録後に「契約条件」タブで調整できます。
              </div>
            </div>
          </div>

          <div className="card card-pad">
            <div className="section-title"><span className="bar" />登録内容の確認</div>
            {items.filter(it => it.name.trim()).length === 0 ? (
              <EmptyState title="見積明細が登録されていません" desc="「見積明細」のステップに戻って入力してください。" />
            ) : (
              <div className="info-grid">
                <div className="info-item"><div className="k">案件番号</div><div className="v">{projectNo}</div></div>
                <div className="info-item"><div className="k">取引区分</div><div className="v">{dealKind === 'receive' ? '受注案件' : '発注案件（協力会社）'}</div></div>
                <div className="info-item"><div className="k">取引先</div><div className="v">{partner?.name ?? '未選択'}</div></div>
                <div className="info-item"><div className="k">工事名称</div><div className="v">{title || '未入力'}</div></div>
                <div className="info-item"><div className="k">工事場所</div><div className="v">{site || '未入力'}</div></div>
                <div className="info-item"><div className="k">明細件数</div><div className="v">{items.filter(it => it.name.trim()).length} 件</div></div>
                <div className="info-item"><div className="k">請負代金（税込）</div><div className="v fw-700">{formatYen(totals.total)}</div></div>
                <div className="info-item"><div className="k">社内担当者</div><div className="v">{staff}</div></div>
              </div>
            )}
          </div>
        </>
      )}

      <div className="row between wrap gap-12 mt-20">
        <button className="btn btn-secondary" onClick={() => (step === 0 ? navigate('/') : setStep(step - 1))}>
          {step === 0 ? 'キャンセル' : '前のステップへ戻る'}
        </button>
        {step < STEPS.length - 1 ? (
          <button className="btn btn-primary btn-lg" onClick={goNext}>
            次へ（{STEPS[step + 1]}）
          </button>
        ) : (
          <button className="btn btn-primary btn-lg" onClick={submit}>
            この内容で見積書を作成する
          </button>
        )}
      </div>
    </>
  );
}
