import { useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import type { ContractTerms, Partner, Project, QuoteFile } from '../types';
import { STAFF_OPTIONS, TERMS_TEMPLATE, quoteFiles } from '../data/sampleData';
import { calcTotals, lineAmount } from '../utils/calc';
import { formatDate, formatDateTime, formatNumber, formatYen, nowIso } from '../utils/format';
import { EmptyState } from '../components/EmptyState';

interface Props {
  partners: Partner[];
  projects: Project[];
  /** ログイン中の利用者名（担当者の初期値と、操作の記録に使う） */
  userName: string;
  onCreate: (project: Project) => void;
  newId: () => string;
  onToast: (message: string, type?: 'success' | 'info' | 'error') => void;
}

const STEPS = ['見積書のファイルを選ぶ', '内容を確認して登録する'];

function nextProjectNo(projects: Project[]): string {
  const max = projects.reduce((acc, p) => {
    const n = Number(p.no.split('-').pop());
    return Number.isNaN(n) ? acc : Math.max(acc, n);
  }, 0);
  return `KJ-2026-${String(max + 1).padStart(4, '0')}`;
}

export function QuoteImport({ partners, projects, userName, onCreate, newId, onToast }: Props) {
  const navigate = useNavigate();
  const [selected, setSelected] = useState<QuoteFile | null>(null);
  const [reading, setReading] = useState(false);
  const [staff, setStaff] = useState(userName);
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [nonWorkingDays, setNonWorkingDays] = useState('');
  const [paymentMethod, setPaymentMethod] = useState('');
  const [errors, setErrors] = useState<Record<string, string>>({});
  const timer = useRef<number | undefined>(undefined);

  useEffect(() => () => window.clearTimeout(timer.current), []);

  const projectNo = useMemo(() => nextProjectNo(projects), [projects]);
  const seqNo = projectNo.split('-').pop() ?? '0000';

  /** 既にこの案件一覧へ取り込んだファイルは、取込待ちから消す */
  const importedNames = useMemo(() => new Set(projects.map(p => p.sourceFile.name)), [projects]);
  const pending = quoteFiles.filter(f => !importedNames.has(f.name));

  const partner = selected ? partners.find(p => p.id === selected.read.partnerId) : undefined;
  const totals = selected ? calcTotals(selected.read.items, selected.read.discount) : null;
  const template = TERMS_TEMPLATE;

  const startReading = (file: QuoteFile) => {
    const target = partners.find(p => p.id === file.read.partnerId);
    setReading(true);
    setErrors({});
    timer.current = window.setTimeout(() => {
      setSelected(file);
      setStartDate(file.read.startDate);
      setEndDate(file.read.endDate);
      setNonWorkingDays(file.read.nonWorkingDays);
      // 支払い方法は取引先マスタの支払条件からそのまま入れる（担当者が打ち直さなくてよい）
      setPaymentMethod(target?.paymentTerms ? `引渡し後、${target.paymentTerms}` : '');
      setReading(false);
      onToast('見積書を読み取りました。内容をご確認ください', 'info');
    }, 900);
  };

  const backToList = () => {
    setSelected(null);
    setErrors({});
  };

  const submit = () => {
    if (!selected || !partner || !totals) return;
    const e: Record<string, string> = {};
    // 工期は任意（注文書を受け取ってから決まることもあるため、あとから案件の画面で入力できる）
    if (startDate && endDate && endDate < startDate) e.endDate = '終わる日は始める日より後にしてください';
    if (!nonWorkingDays.trim()) e.nonWorkingDays = '工事ができない日・時間帯を入力してください';
    if (!paymentMethod.trim()) e.paymentMethod = '代金の支払い方法を入力してください';
    setErrors(e);
    if (Object.keys(e).length > 0) {
      onToast('入力していない項目があります。赤い文字の欄をご確認ください', 'error');
      return;
    }

    const terms: ContractTerms = {
      startDate,
      endDate,
      nonWorkingDays: nonWorkingDays.trim(),
      paymentMethod: paymentMethod.trim(),
    };

    const read = selected.read;
    const project: Project = {
      id: newId(),
      no: projectNo,
      title: read.title,
      status: 'imported',
      partnerId: read.partnerId,
      site: read.site,
      scope: read.scope,
      staff,
      quotedOn: read.quotedOn,
      quoteExpiry: read.quoteExpiry,
      items: read.items.map((it, i) => ({ ...it, id: `it-${seqNo}-${i + 1}` })),
      discount: read.discount,
      sourceFile: { name: selected.name, importedAt: nowIso() },
      terms,
      documents: [
        { kind: 'quote', no: `EST-2026-${seqNo}`, status: 'created', issuedOn: read.quotedOn, autoGenerated: false },
        { kind: 'order', no: '', status: 'none', autoGenerated: false },
        { kind: 'acceptance', no: '', status: 'none', autoGenerated: false },
        { kind: 'terms', no: '', status: 'none', autoGenerated: false },
      ],
      revision: 1,
      history: [
        {
          id: `hx-${seqNo}-1`,
          at: nowIso(),
          actorName: userName,
          action: `見積書ファイル「${selected.name}」を取り込みました`,
        },
      ],
      updatedAt: nowIso(),
    };

    onCreate(project);
    navigate(`/project/${project.id}`);
  };

  const step = selected ? 1 : 0;

  return (
    <>
      <div className="page-head">
        <div>
          <h1 className="page-title">見積書を取り込む</h1>
          <p className="page-sub">
            Excel で作った見積書をそのまま取り込みます。注文書・注文請書・基本契約書（約款）は、この内容から作られます。
          </p>
        </div>
        <button className="btn btn-ghost" onClick={() => navigate('/')}>
          一覧に戻る
        </button>
      </div>

      <ol className="steps" aria-label="取り込みの手順">
        {STEPS.map((label, i) => (
          <li key={label} className={`step ${i === step ? 'active' : i < step ? 'done' : ''}`}>
            <span className="step-no" aria-hidden="true">{i < step ? '✓' : i + 1}</span>
            {label}
          </li>
        ))}
      </ol>

      {reading && (
        <div className="card card-pad reading-card">
          <span className="spinner" aria-hidden="true" />
          <div>
            <div className="fs-17 fw-700">見積書を読み取っています…</div>
            <div className="fs-14 text-sub mt-4">工事名・工事場所・明細・金額を読み取ります。しばらくお待ちください。</div>
          </div>
        </div>
      )}

      {!reading && step === 0 && (
        <div className="card card-pad">
          <h2 className="section-title"><span className="bar" />取り込む見積書のファイルを選んでください</h2>
          <p className="fs-14 text-sub mb-16">
            共有フォルダに保存された見積書ファイルの一覧です。行を押すとその見積書を読み取ります。
          </p>

          {pending.length === 0 ? (
            <EmptyState
              title="取り込み待ちの見積書はありません"
              desc="共有フォルダに保存された見積書は、すべて取り込み済みです。"
              action={
                <button className="btn btn-secondary" onClick={() => navigate('/')}>
                  工事案件の一覧を見る
                </button>
              }
            />
          ) : (
            <ul className="file-list" data-tour="quote-files">
              {pending.map(file => {
                const target = partners.find(p => p.id === file.read.partnerId);
                return (
                  <li key={file.id}>
                    <button className="file-row" onClick={() => startReading(file)}>
                      <span className="file-icon" aria-hidden="true">XLS</span>
                      <span className="file-body">
                        <span className="file-name">{file.name}</span>
                        <span className="file-meta">
                          {target?.name ?? '取引先不明'}
                        </span>
                        <span className="file-meta">
                          保存 {formatDateTime(file.savedAt)}／{file.savedBy}／{formatNumber(file.sizeKb)} KB
                        </span>
                      </span>
                      <span className="file-action">この見積書を取り込む</span>
                    </button>
                  </li>
                );
              })}
            </ul>
          )}
        </div>
      )}

      {!reading && step === 1 && selected && totals && (
        <>
          <div className="alert alert-success mb-16">
            <span aria-hidden="true">✓</span>
            <div>
              <div className="fw-700">見積書を読み取りました</div>
              <div className="fs-14 mt-4">
                「{selected.name}」から、取引先・工事の内容・明細・金額を読み取りました。内容をご確認ください。
              </div>
            </div>
          </div>

          <div className="card card-pad mb-16">
            <h2 className="section-title"><span className="bar" />見積書から読み取った内容</h2>
            <div className="read-grid">
              <ReadItem label="取引先" value={partner?.name ?? '（取引先が未登録です）'} />
              <ReadItem label="工事名" value={selected.read.title} />
              <ReadItem label="工事場所" value={selected.read.site} />
              <ReadItem label="工事の内容" value={selected.read.scope} wide />
              <ReadItem label="見積書の日付" value={formatDate(selected.read.quotedOn)} />
              <ReadItem label="見積の有効期限" value={formatDate(selected.read.quoteExpiry)} />
            </div>

            <div className="table-wrap mt-16">
              <table className="data">
                <thead>
                  <tr>
                    <th>工種・品名</th>
                    <th>仕様・規格</th>
                    <th className="num">数量</th>
                    <th>単位</th>
                    <th className="num">単価</th>
                    <th className="num">金額</th>
                  </tr>
                </thead>
                <tbody>
                  {selected.read.items.map(item => (
                    <tr key={item.id}>
                      <td className="fw-600">{item.name}</td>
                      <td className="fs-13 text-sub">{item.spec}</td>
                      <td className="num">{formatNumber(item.quantity)}</td>
                      <td>{item.unit}</td>
                      <td className="num">{formatYen(item.unitPrice)}</td>
                      <td className="num fw-600">{formatYen(lineAmount(item))}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div className="row end mt-16">
              <div className="total-box">
                <div className="total-line"><span>小計</span><span className="num">{formatYen(totals.subtotal)}</span></div>
                {totals.discount > 0 && (
                  <div className="total-line"><span>値引き</span><span className="num">-{formatYen(totals.discount)}</span></div>
                )}
                <div className="total-line"><span>消費税（10%）</span><span className="num">{formatYen(totals.tax)}</span></div>
                <div className="total-line grand"><span>請負代金（税込）</span><span className="num">{formatYen(totals.total)}</span></div>
              </div>
            </div>

            <p className="fs-13 text-sub mt-12">
              ※ 内容が違う場合は、Excel の見積書を直してから取り込み直してください。
            </p>
          </div>

          <div className="card card-pad mb-16" data-tour="terms-form">
            <h2 className="section-title"><span className="bar" />見積書に書かれていない項目を入力してください</h2>
            <p className="fs-14 text-sub mb-16">
              入力するのはこの4つだけです。ここに入れた内容が、注文書・注文請書・約款にそのまま印字されます。工期は決まっていなければ空欄で大丈夫です。
            </p>

            <div className="form-grid">
              <div className="field">
                <label className="field-label" htmlFor="start">工事を始める日<span className="opt">任意</span></label>
                <input
                  id="start"
                  type="date"
                  className={errors.startDate ? 'input invalid' : 'input'}
                  value={startDate}
                  onChange={e => setStartDate(e.target.value)}
                />
                {errors.startDate && <span className="field-error">{errors.startDate}</span>}
              </div>
              <div className="field">
                <label className="field-label" htmlFor="end">工事が終わる日<span className="opt">任意</span></label>
                <input
                  id="end"
                  type="date"
                  className={errors.endDate ? 'input invalid' : 'input'}
                  value={endDate}
                  onChange={e => setEndDate(e.target.value)}
                />
                {errors.endDate && <span className="field-error">{errors.endDate}</span>}
              </div>
            </div>
            <p className="field-hint mt-4 mb-16">
              工期は任意です。まだ決まっていなければ空欄のままで登録し、注文書を受け取ってから案件の画面で入力できます。
            </p>

            <div className="field">
              <label className="field-label" htmlFor="nonwork">工事ができない日・時間帯<span className="req">必須</span></label>
              <input
                id="nonwork"
                className={errors.nonWorkingDays ? 'input invalid' : 'input'}
                value={nonWorkingDays}
                onChange={e => setNonWorkingDays(e.target.value)}
              />
              {errors.nonWorkingDays && <span className="field-error">{errors.nonWorkingDays}</span>}
              <p className="field-hint">お休みの日や、お客様の稼働中で工事ができない時間帯を書きます。</p>
            </div>

            <div className="field">
              <label className="field-label" htmlFor="payment">代金の支払い方法<span className="req">必須</span></label>
              <input
                id="payment"
                className={errors.paymentMethod ? 'input invalid' : 'input'}
                value={paymentMethod}
                onChange={e => setPaymentMethod(e.target.value)}
              />
              {errors.paymentMethod && <span className="field-error">{errors.paymentMethod}</span>}
              {partner && (
                <p className="field-hint">
                  取引先に登録された支払条件：{partner.paymentTerms || '未登録'}
                  {partner.paymentTerms && (
                    <button
                      className="btn btn-secondary btn-sm ml-8"
                      onClick={() => setPaymentMethod(`引渡し後、${partner.paymentTerms}`)}
                    >
                      この内容を入れる
                    </button>
                  )}
                </p>
              )}
            </div>

            <div className="field" style={{ maxWidth: '340px' }}>
              <label className="field-label" htmlFor="staff">社内の担当者</label>
              <select id="staff" className="select" value={staff} onChange={e => setStaff(e.target.value)}>
                {STAFF_OPTIONS.map(s => (
                  <option key={s} value={s}>{s}</option>
                ))}
              </select>
            </div>

            <div className="alert alert-info">
              <span aria-hidden="true">i</span>
              <div>
                <div className="fw-700">検査・引渡し・遅延利息などの取り決めは入力不要です</div>
                <div className="fs-14 mt-4">
                  「{template.name}」（全 {template.clauses.length} 条）が自動で適用され、検査・引渡しなどの取り決めが書類にそろいます。
                </div>
              </div>
            </div>
          </div>

          <div className="card card-pad mb-16">
            <h2 className="section-title"><span className="bar" />登録する内容</h2>
            <div className="read-grid">
              <ReadItem label="案件番号" value={projectNo} badge={false} />
              <ReadItem label="工事名" value={selected.read.title} badge={false} />
              <ReadItem label="取引先" value={partner?.name ?? '（取引先が未登録です）'} badge={false} />
              <ReadItem label="請負代金（税込）" value={formatYen(totals.total)} strong badge={false} />
              <ReadItem label="工期" value={startDate && endDate ? `${formatDate(startDate)} 〜 ${formatDate(endDate)}` : '未定（あとで入力）'} badge={false} />
              <ReadItem label="社内の担当者" value={staff} badge={false} />
            </div>
          </div>

          <div className="row between wrap gap-12">
            <button className="btn btn-secondary" onClick={backToList}>
              別の見積書を選び直す
            </button>
            <button className="btn btn-primary btn-lg" onClick={submit} data-tour="register-button">
              この内容で登録する
            </button>
          </div>
        </>
      )}
    </>
  );
}

function ReadItem({
  label,
  value,
  wide,
  strong,
  badge = true,
}: {
  label: string;
  value: string;
  wide?: boolean;
  strong?: boolean;
  /** 見積書から読み取った項目には「読み取り済み」を付ける */
  badge?: boolean;
}) {
  return (
    <div className={wide ? 'read-item wide' : 'read-item'}>
      <div className="read-label">
        {label}
        {badge && <span className="read-badge">読み取り済み</span>}
      </div>
      <div className={strong ? 'read-value strong' : 'read-value'}>{value}</div>
    </div>
  );
}
