// 架空のサンプルデータ（実在の企業・個人・案件とは一切関係ありません）

import type {
  ContractTerms,
  DocKind,
  DocStatus,
  DocumentRecord,
  Partner,
  Project,
  QuoteFile,
} from '../types';

/** 自社（デモ上の運営会社。架空） */
export const OWN_COMPANY = {
  name: '株式会社〇〇製作所',
  division: '工事事業部',
  licenseNo: '東京都知事許可（般-6）第00000号',
  postalCode: '000-0000',
  address: '東京都大田区〇〇町0-0-0',
  tel: '03-0000-1234',
  representative: '代表取締役 宮下 泰久',
};

/** ログイン中の利用者（架空） */
export const CURRENT_USER = {
  name: '中村 遥',
  department: '工事事業部 契約管理課',
};

/** 社内担当者の候補（架空） */
export const STAFF_OPTIONS = ['中村 遥', '藤代 悠斗', '小柳 里菜'];

export interface TermsTemplate {
  name: string;
  /** テンプレートに含まれる定型条項。担当者が入力する必要はない */
  clauses: { title: string; body: string }[];
}

/** 約款テンプレート（案件ごとに変わらない取り決めをまとめて持たせる） */
export const TERMS_TEMPLATE: TermsTemplate = {
  name: '工事請負基本契約約款（第3版）',
  clauses: [
    {
      title: '前金払および出来形部分に対する支払',
      body: '前金払および出来形部分に対する支払は行わない。ただし、甲乙協議のうえ書面により別段の定めをすることができる。',
    },
    {
      title: '設計変更・工期の変更',
      body: '甲または乙の申出により設計変更、工事着手の延期または工事の中止が生じた場合、工期の変更、請負代金の額の変更および損害の負担は、甲乙協議のうえ書面により定める。',
    },
    {
      title: '不可抗力による工期の変更・損害の負担',
      body: '天災その他甲乙いずれの責にも帰することができない事由により工期の変更または損害が生じた場合、その負担および額の算定方法は甲乙協議のうえ定める。',
    },
    {
      title: '価格等の変動による請負代金・工事内容の変更',
      body: '資材価格、労務費その他の価格等に著しい変動が生じたときは、甲乙協議のうえ請負代金の額または工事内容を変更することができる。',
    },
    {
      title: '第三者に与えた損害の負担',
      body: '施工に起因して第三者に与えた損害は乙が負担する。ただし、不可抗力による場合および甲の指示に起因する場合はこの限りでない。',
    },
    {
      title: '支給材料および貸与機械',
      body: '支給材料および貸与機械は原則として設けない。設ける場合は、その内容・数量・引渡場所および方法を書面により定める。',
    },
    {
      title: '完成検査および引渡し',
      body: '乙の完成通知の受領後14日以内に甲の立会いのもと完成検査を行い、検査合格後7日以内に引渡しを行う。',
    },
    {
      title: '契約不適合責任',
      body: '乙は、工事目的物に契約の内容に適合しない部分があるときは、引渡しの日から2年間（設備機器は1年間）その責任を負う。',
    },
    {
      title: '履行遅滞・違約金',
      body: '履行遅滞その他債務不履行が生じた場合は、年率3.0％の遅延利息を付す。',
    },
    {
      title: '紛争の解決',
      body: '本契約に関する紛争は甲乙協議のうえ解決し、協議が調わない場合は建設工事紛争審査会のあっせんまたは調停による。',
    },
  ],
};

export const partners: Partner[] = [
  {
    id: 'p-01',
    name: '株式会社〇〇建設',
    department: '建築工事部 工事課',
    contactName: '大森 健太',
    postalCode: '000-0000',
    address: '東京都江東区〇〇0-0-0 〇〇ビル8F',
    tel: '03-0000-2201',
    paymentTerms: '月末締め翌月末 銀行振込',
  },
  {
    id: 'p-02',
    name: '〇〇不動産株式会社',
    department: '施設管理部',
    contactName: '白石 紗代',
    postalCode: '000-0000',
    address: '神奈川県横浜市西区〇〇0-0-0',
    tel: '045-0000-3310',
    paymentTerms: '20日締め翌月20日 銀行振込',
  },
  {
    id: 'p-03',
    name: '株式会社〇〇食品工業',
    department: '生産技術課',
    contactName: '及川 亮',
    postalCode: '000-0000',
    address: '埼玉県川越市〇〇0-0-0',
    tel: '049-0000-4412',
    paymentTerms: '月末締め翌々月10日 銀行振込',
  },
  {
    id: 'p-04',
    name: '〇〇電機株式会社',
    department: '総務部 施設グループ',
    contactName: '村瀬 直人',
    postalCode: '000-0000',
    address: '千葉県船橋市〇〇0-0-0',
    tel: '047-0000-5523',
    paymentTerms: '月末締め翌月末 銀行振込',
  },
  {
    id: 'p-05',
    name: '〇〇倉庫運輸株式会社',
    department: '物流管理部',
    contactName: '伊丹 桂子',
    postalCode: '000-0000',
    address: '東京都江戸川区〇〇0-0-0',
    tel: '03-0000-6634',
    paymentTerms: '月末締め翌月末 銀行振込',
  },
];

const DOC_PREFIX: Record<DocKind, string> = {
  quote: 'EST',
  order: 'ORD',
  acceptance: 'ACC',
  terms: 'AGR',
};

/** 4点セットの書類レコードを組み立てる */
function buildDocs(
  seq: string,
  statuses: Record<DocKind, DocStatus>,
  issuedOn: Partial<Record<DocKind, string>>,
  revision = 1,
): DocumentRecord[] {
  return (Object.keys(DOC_PREFIX) as DocKind[]).map(kind => {
    const status = statuses[kind];
    if (status === 'none') {
      return { kind, no: '', status, autoGenerated: false };
    }
    return {
      kind,
      no: `${DOC_PREFIX[kind]}-2026-${seq}`,
      status,
      issuedOn: issuedOn[kind],
      autoGenerated: kind !== 'quote',
      sourceRevision: kind === 'quote' ? undefined : revision,
    };
  });
}

/** 工事の条件。未入力の欄は「書類に必要な項目」で不足として検知される */
function terms(partial: Partial<ContractTerms>): ContractTerms {
  return {
    startDate: '',
    endDate: '',
    nonWorkingDays: '日曜日および年末年始（12/29〜1/3）',
    paymentMethod: '',
    ...partial,
  };
}

function history(entries: [string, string, string][]): Project['history'] {
  return entries.map(([at, actorName, action], i) => ({
    id: `hx-${at}-${i}`,
    at,
    actorName,
    action,
  }));
}

export const sampleProjects: Project[] = [
  {
    id: 'kj-0031',
    no: 'KJ-2026-0031',
    title: '〇〇物流センター 加工ライン架台製作および据付工事',
    status: 'accepted',
    partnerId: 'p-01',
    site: '千葉県市原市〇〇0-0-0 〇〇物流センター内',
    scope: '鋼製架台の製作・搬入・据付、既存基礎のはつりおよびアンカー打設一式',
    staff: '中村 遥',
    quotedOn: '2026-08-03',
    quoteExpiry: '2026-09-02',
    items: [
      { id: 'it-1', name: '鋼製架台製作', spec: 'SS400 溶融亜鉛めっき仕上げ W2400×D1200×H1800', quantity: 4, unit: '基', unitPrice: 385000 },
      { id: 'it-2', name: '既存基礎はつり', spec: 'コンクリートはつり・産廃処分共', quantity: 1, unit: '式', unitPrice: 240000 },
      { id: 'it-3', name: 'アンカー打設', spec: 'ケミカルアンカー M16 埋込150mm', quantity: 48, unit: '本', unitPrice: 3800 },
      { id: 'it-4', name: '搬入・据付調整', spec: '4t ユニック車・作業員3名×2日', quantity: 2, unit: '日', unitPrice: 168000 },
      { id: 'it-5', name: '現場管理費', spec: '安全管理・仮設・書類作成共', quantity: 1, unit: '式', unitPrice: 195000 },
    ],
    discount: 40000,
    sourceFile: { name: '見積書_〇〇物流センター架台工事_20260803.xlsx', importedAt: '2026-08-03T10:20:00' },
    terms: terms({
      startDate: '2026-09-14',
      endDate: '2026-10-16',
      paymentMethod: '引渡し後、月末締め翌月末 銀行振込',
      nonWorkingDays: '日曜日および施設の入出荷ピーク日（毎月25日）',
    }),
    documents: buildDocs(
      '0031',
      { quote: 'created', order: 'sealed', acceptance: 'sent', terms: 'sealed' },
      { quote: '2026-08-03', order: '2026-08-20', acceptance: '2026-08-24', terms: '2026-08-24' },
    ),
    revision: 1,
    history: history([
      ['2026-08-03T10:20:00', '中村 遥', '見積書ファイル「見積書_〇〇物流センター架台工事_20260803.xlsx」を取り込みました'],
      ['2026-08-20T09:40:00', '中村 遥', '見積書の内容から注文書・注文請書・基本契約書（約款）を作成しました'],
      ['2026-08-20T16:30:00', '中村 遥', '押印済みの注文書・基本契約書（約款）を受け取りました。基本契約書（約款）は締結済みです'],
      ['2026-08-24T11:10:00', '中村 遥', '注文請書を送付し、契約成立としました'],
    ]),
    updatedAt: '2026-08-24T11:10:00',
    bundleFileName: 'KJ-2026-0031_工事関係書類一式.pdf',
  },
  {
    id: 'kj-0034',
    no: 'KJ-2026-0034',
    title: '〇〇食品工場 冷却設備更新に伴う配管改修工事',
    status: 'ordered',
    partnerId: 'p-03',
    site: '埼玉県川越市〇〇0-0-0 第2工場',
    scope: '冷却水配管の撤去・新設、保温工事、試運転調整',
    staff: '藤代 悠斗',
    quotedOn: '2026-08-21',
    quoteExpiry: '2026-09-20',
    items: [
      { id: 'it-1', name: '既存配管撤去', spec: 'SGP 65A 約60m・保温材共', quantity: 1, unit: '式', unitPrice: 320000 },
      { id: 'it-2', name: '配管新設', spec: 'SUS304 65A 溶接接合 約60m', quantity: 60, unit: 'm', unitPrice: 12800 },
      { id: 'it-3', name: '保温工事', spec: 'グラスウール25mm ラッキング仕上げ', quantity: 60, unit: 'm', unitPrice: 4200 },
      { id: 'it-4', name: '試運転調整', spec: '流量・漏れ確認、記録提出共', quantity: 1, unit: '式', unitPrice: 145000 },
    ],
    discount: 0,
    sourceFile: { name: '見積書_〇〇食品工場_配管改修_20260821.xlsx', importedAt: '2026-08-21T13:15:00' },
    terms: terms({
      startDate: '2026-09-27',
      endDate: '2026-10-25',
      nonWorkingDays: '工場稼働日（施工は日曜日のみ）',
      paymentMethod: '引渡し後、月末締め翌々月10日 銀行振込',
    }),
    documents: buildDocs(
      '0034',
      { quote: 'created', order: 'sealed', acceptance: 'created', terms: 'sealed' },
      { quote: '2026-08-21', order: '2026-09-04', acceptance: '2026-09-04', terms: '2026-09-04' },
    ),
    revision: 1,
    history: history([
      ['2026-08-21T13:15:00', '藤代 悠斗', '見積書ファイル「見積書_〇〇食品工場_配管改修_20260821.xlsx」を取り込みました'],
      ['2026-09-04T09:05:00', '中村 遥', '見積書の内容から注文書・注文請書・基本契約書（約款）を作成しました'],
      ['2026-09-07T14:20:00', '中村 遥', '押印済みの注文書・基本契約書（約款）を受け取りました。基本契約書（約款）は締結済みです'],
    ]),
    updatedAt: '2026-09-07T14:20:00',
  },
  {
    id: 'kj-0036',
    no: 'KJ-2026-0036',
    title: '〇〇ビル 4階事務室 間仕切り新設工事',
    status: 'imported',
    partnerId: 'p-02',
    site: '神奈川県横浜市西区〇〇0-0-0 〇〇ビル4F',
    scope: 'LGS下地・石膏ボード張り間仕切りの新設、建具設置、内装仕上げ',
    staff: '中村 遥',
    quotedOn: '2026-09-02',
    quoteExpiry: '2026-10-02',
    items: [
      { id: 'it-1', name: 'LGS下地組', spec: '65形 @455 H2700 延長32m', quantity: 32, unit: 'm', unitPrice: 8600 },
      { id: 'it-2', name: '石膏ボード張り', spec: '12.5mm 両面張り・目地処理共', quantity: 172, unit: '㎡', unitPrice: 3400 },
      { id: 'it-3', name: '片開き建具設置', spec: 'スチールドア W900×H2000 錠前共', quantity: 2, unit: '箇所', unitPrice: 148000 },
      { id: 'it-4', name: 'クロス仕上げ', spec: '量産品クロス 施工面積172㎡', quantity: 172, unit: '㎡', unitPrice: 1450 },
      { id: 'it-5', name: '廃材処分費', spec: '産業廃棄物 マニフェスト発行共', quantity: 1, unit: '式', unitPrice: 88000 },
    ],
    discount: 25000,
    sourceFile: { name: '見積書_〇〇ビル4F_間仕切り新設_20260902.xlsx', importedAt: '2026-09-02T11:30:00' },
    terms: terms({
      startDate: '2026-10-05',
      endDate: '2026-10-30',
      paymentMethod: '引渡し後、20日締め翌月20日 銀行振込',
    }),
    documents: buildDocs('0036', { quote: 'created', order: 'none', acceptance: 'none', terms: 'none' }, { quote: '2026-09-02' }),
    revision: 1,
    history: history([
      ['2026-09-02T11:30:00', '中村 遥', '見積書ファイル「見積書_〇〇ビル4F_間仕切り新設_20260902.xlsx」を取り込みました'],
    ]),
    updatedAt: '2026-09-02T11:30:00',
  },
  {
    id: 'kj-0037',
    no: 'KJ-2026-0037',
    title: '〇〇電機 本社棟 屋上防水改修工事',
    status: 'imported',
    partnerId: 'p-04',
    site: '千葉県船橋市〇〇0-0-0 本社棟屋上',
    scope: '既存アスファルト防水の下地調整、ウレタン塗膜防水（X-1工法）、脱気筒設置',
    staff: '藤代 悠斗',
    quotedOn: '2026-09-05',
    quoteExpiry: '2026-10-05',
    items: [
      { id: 'it-1', name: '仮設足場・養生', spec: '荷揚げ用簡易リフト共', quantity: 1, unit: '式', unitPrice: 265000 },
      { id: 'it-2', name: '下地調整', spec: '高圧洗浄・ひび割れ補修 420㎡', quantity: 420, unit: '㎡', unitPrice: 1250 },
      { id: 'it-3', name: 'ウレタン塗膜防水', spec: 'X-1工法 通気緩衝シート張り 420㎡', quantity: 420, unit: '㎡', unitPrice: 6800 },
      { id: 'it-4', name: '脱気筒設置', spec: 'ステンレス製 φ75', quantity: 8, unit: '箇所', unitPrice: 14500 },
    ],
    discount: 0,
    sourceFile: { name: '見積書_〇〇電機本社棟_屋上防水_20260905.xlsx', importedAt: '2026-09-05T09:50:00' },
    terms: terms({
      startDate: '2026-10-12',
      endDate: '2026-11-27',
      paymentMethod: '引渡し後、月末締め翌月末 銀行振込',
    }),
    documents: buildDocs('0037', { quote: 'created', order: 'none', acceptance: 'none', terms: 'none' }, { quote: '2026-09-05' }),
    revision: 1,
    history: history([
      ['2026-09-05T09:50:00', '藤代 悠斗', '見積書ファイル「見積書_〇〇電機本社棟_屋上防水_20260905.xlsx」を取り込みました'],
    ]),
    updatedAt: '2026-09-05T09:50:00',
  },
  {
    id: 'kj-0038',
    no: 'KJ-2026-0038',
    title: '〇〇倉庫 夜間 照明LED化工事',
    status: 'imported',
    partnerId: 'p-05',
    site: '東京都江戸川区〇〇0-0-0 〇〇第3倉庫',
    scope: '既存水銀灯の撤去、高天井用LED照明への交換、点灯確認',
    staff: '中村 遥',
    quotedOn: '2026-09-09',
    quoteExpiry: '2026-10-09',
    items: [
      { id: 'it-1', name: '既存水銀灯撤去', spec: '400W 高天井用・処分共', quantity: 42, unit: '台', unitPrice: 6800 },
      { id: 'it-2', name: '高天井用LED照明設置', spec: '150W相当 電源内蔵型', quantity: 42, unit: '台', unitPrice: 32800 },
      { id: 'it-3', name: '高所作業車費用', spec: '12m級・オペレーター共', quantity: 4, unit: '日', unitPrice: 58000 },
    ],
    discount: 0,
    sourceFile: { name: '見積書_〇〇第3倉庫_照明LED化_20260909.xlsx', importedAt: '2026-09-09T17:05:00' },
    terms: terms({
      startDate: '',
      endDate: '',
      nonWorkingDays: '倉庫稼働時間帯（8:00〜20:00）',
      paymentMethod: '',
    }),
    documents: buildDocs('0038', { quote: 'created', order: 'none', acceptance: 'none', terms: 'none' }, { quote: '2026-09-09' }),
    revision: 1,
    history: history([
      ['2026-09-09T17:05:00', '中村 遥', '見積書ファイル「見積書_〇〇第3倉庫_照明LED化_20260909.xlsx」を取り込みました'],
    ]),
    updatedAt: '2026-09-09T17:05:00',
  },
  {
    id: 'kj-0028',
    no: 'KJ-2026-0028',
    title: '〇〇不動産 〇〇マンション 外壁タイル補修工事',
    status: 'completed',
    partnerId: 'p-02',
    site: '神奈川県横浜市港北区〇〇0-0-0',
    scope: '浮きタイルの斫り・張替え、シーリング打替え、部分塗装',
    staff: '藤代 悠斗',
    quotedOn: '2026-06-15',
    quoteExpiry: '2026-07-15',
    items: [
      { id: 'it-1', name: '仮設足場', spec: 'くさび式 380㎡・メッシュシート共', quantity: 380, unit: '㎡', unitPrice: 1250 },
      { id: 'it-2', name: 'タイル張替え', spec: '45二丁掛 既存同等品 96㎡', quantity: 96, unit: '㎡', unitPrice: 14800 },
      { id: 'it-3', name: 'シーリング打替え', spec: '変成シリコーン 240m', quantity: 240, unit: 'm', unitPrice: 1450 },
      { id: 'it-4', name: '部分塗装', spec: '水性シリコン 2回塗り 64㎡', quantity: 64, unit: '㎡', unitPrice: 3200 },
    ],
    discount: 120000,
    sourceFile: { name: '見積書_〇〇マンション_外壁タイル補修_20260615.xlsx', importedAt: '2026-06-15T10:05:00' },
    terms: terms({
      startDate: '2026-07-06',
      endDate: '2026-08-21',
      paymentMethod: '引渡し後、20日締め翌月20日 銀行振込',
    }),
    documents: buildDocs(
      '0028',
      { quote: 'created', order: 'sealed', acceptance: 'sealed', terms: 'sealed' },
      { quote: '2026-06-15', order: '2026-06-26', acceptance: '2026-06-30', terms: '2026-06-30' },
    ),
    revision: 1,
    history: history([
      ['2026-06-15T10:05:00', '藤代 悠斗', '見積書ファイル「見積書_〇〇マンション_外壁タイル補修_20260615.xlsx」を取り込みました'],
      ['2026-06-26T11:20:00', '藤代 悠斗', '見積書の内容から注文書・注文請書・基本契約書（約款）を作成しました'],
      ['2026-06-30T15:30:00', '中村 遥', '注文請書を送付し、契約成立としました'],
      ['2026-08-21T17:00:00', '藤代 悠斗', '工事完了・引渡しを登録しました'],
    ]),
    updatedAt: '2026-08-21T17:00:00',
    bundleFileName: 'KJ-2026-0028_工事関係書類一式.pdf',
  },
];

/**
 * 取込待ちの見積書ファイル。
 * Excel で作成し共有フォルダへ保存した見積書を、システムが読み取る想定のサンプル。
 */
export const quoteFiles: QuoteFile[] = [
  {
    id: 'qf-01',
    name: '見積書_〇〇建設_〇〇工場 排気ダクト更新_20260915.xlsx',
    savedAt: '2026-09-15T14:05:00',
    savedBy: '中村 遥',
    sizeKb: 78,
    read: {
      partnerId: 'p-01',
      title: '〇〇工場 排気ダクト更新工事',
      site: '東京都大田区〇〇0-0-0 〇〇工場 第2棟',
      scope: '既存排気ダクトの撤去、亜鉛鉄板ダクトの新設、送風機の取替えおよび風量調整',
      quotedOn: '2026-09-15',
      quoteExpiry: '2026-10-15',
      items: [
        { id: 'qi-1', name: '既存ダクト撤去', spec: '亜鉛鉄板 500×300 約38m・処分共', quantity: 1, unit: '式', unitPrice: 268000 },
        { id: 'qi-2', name: 'ダクト新設', spec: '亜鉛鉄板 600×400 保温25mm共 38m', quantity: 38, unit: 'm', unitPrice: 18600 },
        { id: 'qi-3', name: '送風機取替え', spec: '有圧換気扇 φ500 三相200V', quantity: 3, unit: '台', unitPrice: 142000 },
        { id: 'qi-4', name: '風量調整・試運転', spec: '測定記録の提出共', quantity: 1, unit: '式', unitPrice: 98000 },
        { id: 'qi-5', name: '現場管理費', spec: '安全管理・仮設共', quantity: 1, unit: '式', unitPrice: 155000 },
      ],
      discount: 30000,
      startDate: '',
      endDate: '',
      nonWorkingDays: '日曜日および年末年始（12/29〜1/3）',
    },
  },
  {
    id: 'qf-02',
    name: '見積書_〇〇不動産_〇〇ビル 給水ポンプ更新_20260914.xlsx',
    savedAt: '2026-09-14T17:40:00',
    savedBy: '藤代 悠斗',
    sizeKb: 66,
    read: {
      partnerId: 'p-02',
      title: '〇〇ビル 給水ポンプユニット更新工事',
      site: '神奈川県横浜市西区〇〇0-0-0 〇〇ビル 地下機械室',
      scope: '既存給水ポンプユニットの撤去・搬出、新設ユニットの据付、配管接続および試運転',
      quotedOn: '2026-09-14',
      quoteExpiry: '2026-10-14',
      items: [
        { id: 'qi-1', name: '既存ポンプ撤去・搬出', spec: '加圧給水ユニット 2.2kW×2・処分共', quantity: 1, unit: '式', unitPrice: 185000 },
        { id: 'qi-2', name: '給水ポンプユニット設置', spec: 'インバータ式 2.2kW×2 制御盤共', quantity: 1, unit: '基', unitPrice: 1280000 },
        { id: 'qi-3', name: '配管接続工事', spec: 'SUS304 50A フレキ継手共', quantity: 1, unit: '式', unitPrice: 246000 },
        { id: 'qi-4', name: '電気接続・試運転', spec: '絶縁測定・水質確認共', quantity: 1, unit: '式', unitPrice: 132000 },
      ],
      discount: 0,
      startDate: '',
      endDate: '',
      nonWorkingDays: '日曜日および年末年始（12/29〜1/3）',
    },
  },
];
