// 取り込んだ見積書の内容から注文書・注文請書・基本契約書（約款）を組み立てるロジックと、
// 「書類に必要な項目」がそろっているかのチェック

import type {
  ComplianceItem,
  DocKind,
  DocStatus,
  DocumentRecord,
  Partner,
  Project,
} from '../types';
import { DOC_STATUS_LABELS } from '../types';
import { OWN_COMPANY, termsTemplate } from '../data/sampleData';
import { calcTotals } from './calc';
import { formatDate, formatYen } from './format';

export interface PartyInfo {
  label: string;
  name: string;
  address: string;
  tel: string;
  contact: string;
  licenseNo: string;
}

/** 案件の取引区分に応じて、注文者（甲）と受注者（乙）を決める */
export function partiesOf(project: Project, partner: Partner): { orderer: PartyInfo; contractor: PartyInfo } {
  const own: PartyInfo = {
    label: '',
    name: `${OWN_COMPANY.name} ${OWN_COMPANY.division}`,
    address: `〒${OWN_COMPANY.postalCode} ${OWN_COMPANY.address}`,
    tel: OWN_COMPANY.tel,
    contact: OWN_COMPANY.representative,
    licenseNo: OWN_COMPANY.licenseNo,
  };
  const other: PartyInfo = {
    label: '',
    name: partner.name,
    address: `〒${partner.postalCode} ${partner.address}`,
    tel: partner.tel,
    contact: `${partner.department} ${partner.contactName} 様`,
    licenseNo: partner.licenseNo,
  };
  if (project.dealKind === 'receive') {
    return {
      orderer: { ...other, label: '注文者（甲）' },
      contractor: { ...own, label: '受注者（乙）' },
    };
  }
  return {
    orderer: { ...own, label: '注文者（甲）' },
    contractor: { ...other, label: '受注者（乙）' },
  };
}

/** 書類ごとの「誰が誰に出すか」を短い日本語で説明する */
export function docFlowNote(project: Project, kind: DocKind, partner: Partner): string {
  const isReceive = project.dealKind === 'receive';
  switch (kind) {
    case 'quote':
      return isReceive
        ? `${partner.name} へお出しした見積書です。`
        : `${partner.name} から受け取った見積書です。`;
    case 'order':
      return isReceive
        ? `${partner.name} からいただく注文書です。先方が注文書を出さない場合は、この書類に押印をいただくだけで済みます。`
        : `${partner.name} へお渡しする注文書です。`;
    case 'acceptance':
      return isReceive
        ? `${partner.name} へお渡しする注文請書です。`
        : `${partner.name} からいただく注文請書です。`;
    case 'terms':
      return '工期・支払いなどの約束ごとをまとめた書類です。注文書・注文請書と一緒に保管します。';
  }
}

/** 見積書は「作成」ではなく「取込」なので、状態の呼び方を書類ごとに変える */
export function docStatusLabel(kind: DocKind, status: DocStatus): string {
  if (kind === 'quote') {
    return status === 'none' ? '未取込' : '取込済み';
  }
  return DOC_STATUS_LABELS[status];
}

const DOC_PREFIX: Record<DocKind, string> = {
  quote: 'EST',
  order: 'ORD',
  acceptance: 'ACC',
  terms: 'AGR',
};

/** 案件番号 KJ-2026-0031 から連番部分（0031）を取り出す */
function seqOf(projectNo: string): string {
  const parts = projectNo.split('-');
  return parts[parts.length - 1] ?? '0000';
}

export function documentNo(project: Project, kind: DocKind): string {
  return `${DOC_PREFIX[kind]}-2026-${seqOf(project.no)}`;
}

/** 見積書をもとに注文書・注文請書・約款を自動生成した書類レコードを返す */
export function generateDocuments(project: Project, issuedOn: string): DocumentRecord[] {
  return project.documents.map(doc => {
    if (doc.kind === 'quote') return doc;
    return {
      kind: doc.kind,
      no: documentNo(project, doc.kind),
      // 既に送付・押印済みの書類は進捗を戻さず、内容だけ最新の見積書に合わせる
      status: doc.status === 'none' ? 'created' : doc.status,
      issuedOn,
      autoGenerated: true,
      sourceRevision: project.revision,
    };
  });
}

/** 3書類（注文書・注文請書・約款）が作成済みか */
export function isGenerated(project: Project): boolean {
  return project.documents.filter(d => d.kind !== 'quote').every(d => d.status !== 'none');
}

/** 見積書を差し替えたあと、3書類の作り直しが必要か */
export function needsRegenerate(project: Project): boolean {
  return project.documents.some(
    d => d.kind !== 'quote' && d.status !== 'none' && (d.sourceRevision ?? 0) < project.revision,
  );
}

/** 4点セットが揃っているか */
export function isDocSetComplete(project: Project): boolean {
  return project.documents.every(d => d.status !== 'none');
}

/**
 * 書類に必要な項目のチェック。
 * 担当者が読んで分かる言葉を主役にし、根拠となる条文は補足として添える。
 * 定型条項は約款テンプレートが持つため、入力が必要な項目は最小限になっている。
 */
export function buildComplianceItems(project: Project, partner: Partner): ComplianceItem[] {
  const t = project.terms;
  const totals = calcTotals(project.items, project.discount);
  const template = termsTemplate(t.termsTemplateId);

  const items: ComplianceItem[] = [
    {
      label: '取引先の会社名・所在地・連絡先',
      ok: Boolean(partner.name && partner.address && partner.tel),
      value: `${partner.name}／${partner.address}`,
      hint: '「取引先」の画面で、会社名・所在地・電話番号を登録してください。',
      clause: '建設業法 第19条第1項第16号',
    },
    {
      label: '工事の名称・場所・内容',
      ok: Boolean(project.title.trim() && project.site.trim() && project.scope.trim()) && project.items.length > 0,
      value: `${project.title}（${project.site}）`,
      hint: '見積書の読み取り結果に不足があります。「見積書の内容」から見積書を差し替えてください。',
      clause: '建設業法 第19条第1項第1号・第20条',
    },
    {
      label: '請負代金の額',
      ok: totals.total > 0,
      value: `${formatYen(totals.total)}（税込）`,
      hint: '見積書から金額を読み取れていません。「見積書の内容」から見積書を差し替えてください。',
      clause: '建設業法 第19条第1項第2号',
    },
    {
      label: '工期（着手日と完成日）',
      ok: Boolean(t.startDate && t.endDate),
      value: t.startDate && t.endDate ? `${formatDate(t.startDate)} 〜 ${formatDate(t.endDate)}` : '',
      hint: '「見積書の内容」タブの「工事の条件」で、着手日と完成日を入力してください。',
      clause: '建設業法 第19条第1項第3号',
    },
    {
      label: '工事ができない日・時間帯',
      ok: t.nonWorkingDays.trim().length > 0,
      value: t.nonWorkingDays,
      hint: '「見積書の内容」タブの「工事の条件」で、休工日や施工できない時間帯を入力してください。',
      clause: '建設業法 第19条第1項第4号',
    },
    {
      label: '代金の支払い方法',
      ok: t.paymentMethod.trim().length > 0,
      value: t.paymentMethod,
      hint: '「見積書の内容」タブの「工事の条件」で、支払い方法を入力してください。取引先の支払条件から入力できます。',
      clause: '建設業法 第19条第1項第12号',
    },
    {
      label: 'その他の取り決め（検査・引渡し・不可抗力など）',
      ok: Boolean(t.termsTemplateId),
      value: `${template.name}（${template.clauses.length}条）を自動で適用`,
      hint: '「見積書の内容」タブの「工事の条件」で、使用する約款を選んでください。',
      clause: '建設業法 第19条第1項第5〜11・13〜15号',
    },
  ];

  if (project.dealKind === 'order') {
    items.push({
      label: '協力会社の建設業許可番号',
      ok: partner.licenseNo.trim().length > 0,
      value: partner.licenseNo,
      hint: '「取引先」の画面で、協力会社の建設業許可番号を登録してください。',
      clause: '建設業法 第40条の3ほか',
    });
  }

  return items;
}

export function complianceSummary(items: ComplianceItem[]): { ok: number; total: number; rate: number } {
  const ok = items.filter(i => i.ok).length;
  const total = items.length;
  return { ok, total, rate: total === 0 ? 0 : Math.round((ok / total) * 100) };
}

export interface Article {
  no: string;
  title: string;
  body: string;
  /** 約款テンプレートから自動で付く条項かどうか */
  fromTemplate: boolean;
}

/**
 * 約款の条文を組み立てる。
 * 案件ごとに決めた条件（工期・支払いなど）＋約款テンプレートの定型条項。
 */
export function buildArticles(project: Project, partner: Partner): Article[] {
  const t = project.terms;
  const totals = calcTotals(project.items, project.discount);
  const parties = partiesOf(project, partner);
  const template = termsTemplate(t.termsTemplateId);
  const na = (v: string, fallback: string) => (v.trim() ? v.trim() : fallback);
  const period =
    t.startDate && t.endDate
      ? `着手 ${formatDate(t.startDate)}、完成 ${formatDate(t.endDate)}`
      : '未定（「工事の条件」で着手日・完成日を入力してください）';

  const own: Article[] = [
    {
      no: '第1条',
      title: '総則',
      body: `${parties.orderer.name}（以下「甲」という。）と ${parties.contractor.name}（以下「乙」という。）は、${project.title} に関する工事請負契約について、本約款の定めるところにより誠実に履行する。`,
      fromTemplate: false,
    },
    {
      no: '第2条',
      title: '工事内容',
      body: `工事名 ${project.title}／工事場所 ${project.site}／工事内容 ${project.scope}。詳細は見積書 ${documentNo(project, 'quote')} の明細による。`,
      fromTemplate: false,
    },
    {
      no: '第3条',
      title: '請負代金の額',
      body: `請負代金の額は ${formatYen(totals.total)}（うち消費税額等 ${formatYen(totals.tax)}）とする。`,
      fromTemplate: false,
    },
    {
      no: '第4条',
      title: '工期',
      body: `工期は ${period} とする。`,
      fromTemplate: false,
    },
    {
      no: '第5条',
      title: '工事を施工しない日または時間帯',
      body: na(t.nonWorkingDays, '別途甲乙協議のうえ定める。'),
      fromTemplate: false,
    },
    {
      no: '第6条',
      title: '請負代金の支払',
      body: `${na(t.paymentMethod, '完成後の請負代金の支払時期および方法は甲乙協議のうえ定める。')} 支払条件は「${partner.paymentTerms}」による。`,
      fromTemplate: false,
    },
  ];

  const fromTemplate: Article[] = template.clauses.map((c, i) => ({
    no: `第${own.length + i + 1}条`,
    title: c.title,
    body: c.body,
    fromTemplate: true,
  }));

  return [...own, ...fromTemplate];
}
