// 見積書データから注文書・注文請書・基本契約書（約款）を組み立てるロジックと、
// 建設業法（第19条第1項ほか）の記載事項チェック

import type {
  ComplianceItem,
  DocKind,
  DocumentRecord,
  Partner,
  Project,
} from '../types';
import { OWN_COMPANY } from '../data/sampleData';
import { calcTotals } from './calc';
import { formatDate, formatYen } from './format';

export interface PartyInfo {
  label: string;
  name: string;
  address: string;
  tel: string;
  contact: string;
  licenseNo: string;
}

/** 案件の取引区分に応じて、注文者（甲）と受注者（乙）を決める */
export function partiesOf(project: Project, partner: Partner): { orderer: PartyInfo; contractor: PartyInfo } {
  const own: PartyInfo = {
    label: '',
    name: `${OWN_COMPANY.name} ${OWN_COMPANY.division}`,
    address: `〒${OWN_COMPANY.postalCode} ${OWN_COMPANY.address}`,
    tel: OWN_COMPANY.tel,
    contact: OWN_COMPANY.representative,
    licenseNo: OWN_COMPANY.licenseNo,
  };
  const other: PartyInfo = {
    label: '',
    name: partner.name,
    address: `〒${partner.postalCode} ${partner.address}`,
    tel: partner.tel,
    contact: `${partner.department} ${partner.contactName} 様`,
    licenseNo: partner.licenseNo,
  };
  if (project.dealKind === 'receive') {
    return {
      orderer: { ...other, label: '注文者（甲）' },
      contractor: { ...own, label: '受注者（乙）' },
    };
  }
  return {
    orderer: { ...own, label: '注文者（甲）' },
    contractor: { ...other, label: '受注者（乙）' },
  };
}

/** 書類ごとの「誰が誰に出すか」を日本語で説明する */
export function docFlowNote(project: Project, kind: DocKind, partner: Partner): string {
  const isReceive = project.dealKind === 'receive';
  switch (kind) {
    case 'quote':
      return isReceive
        ? `当社が ${partner.name} へ提出する見積書です。`
        : `${partner.name} から受領した見積書です。`;
    case 'order':
      return isReceive
        ? `${partner.name} が注文者となる注文書です。先方が注文書を発行しない場合は、この自動生成分に記名押印をいただくことで対応できます。`
        : `当社が注文者として ${partner.name} へ発行する注文書です。`;
    case 'acceptance':
      return isReceive
        ? `当社が受注者として ${partner.name} へ発行する注文請書です。`
        : `${partner.name} から受領する注文請書です。押印後に返送されたものを登録します。`;
    case 'terms':
      return '見積条件と契約条件を反映した基本契約書（約款）です。注文書・注文請書と一体で保管します。';
  }
}

const DOC_PREFIX: Record<DocKind, string> = {
  quote: 'EST',
  order: 'ORD',
  acceptance: 'ACC',
  terms: 'AGR',
};

/** 案件番号 KJ-2026-0031 から連番部分（0031）を取り出す */
function seqOf(projectNo: string): string {
  const parts = projectNo.split('-');
  return parts[parts.length - 1] ?? '0000';
}

export function documentNo(project: Project, kind: DocKind): string {
  return `${DOC_PREFIX[kind]}-2026-${seqOf(project.no)}`;
}

/** 見積書をもとに注文書・注文請書・約款を自動生成した書類レコードを返す */
export function generateDocuments(project: Project, issuedOn: string): DocumentRecord[] {
  return project.documents.map(doc => {
    if (doc.kind === 'quote') return doc;
    return {
      kind: doc.kind,
      no: documentNo(project, doc.kind),
      // 既に送付・押印済みの書類は進捗を戻さず、内容だけ最新の見積に合わせる
      status: doc.status === 'none' ? 'created' : doc.status,
      issuedOn,
      autoGenerated: true,
      sourceRevision: project.revision,
    };
  });
}

/** 見積を変更したあと、自動生成書類の再生成が必要か */
export function needsRegenerate(project: Project): boolean {
  return project.documents.some(
    d => d.kind !== 'quote' && d.status !== 'none' && (d.sourceRevision ?? 0) < project.revision,
  );
}

/** 4点セットが揃っているか */
export function isDocSetComplete(project: Project): boolean {
  return project.documents.every(d => d.status !== 'none');
}

/** 建設業法の記載事項チェック（第19条第1項各号ほか） */
export function buildComplianceItems(project: Project, partner: Partner): ComplianceItem[] {
  const t = project.terms;
  const totals = calcTotals(project.items, project.discount);
  const hasTemplate = Boolean(t.termsTemplateId);
  const items: ComplianceItem[] = [
    {
      clause: '第19条第1項第1号',
      label: '工事内容',
      ok: project.scope.trim().length > 0 && project.items.length > 0,
      hint: '「見積明細」タブで工事内容と明細を登録してください。',
    },
    {
      clause: '第19条第1項第2号',
      label: '請負代金の額',
      ok: totals.total > 0,
      hint: '「見積明細」タブで数量・単価を入力すると請負代金の額が確定します。',
    },
    {
      clause: '第19条第1項第3号',
      label: '工事着手の時期および工事完成の時期',
      ok: Boolean(t.startDate && t.endDate),
      hint: '「契約条件」タブで着手日と完成日を入力してください。',
    },
    {
      clause: '第19条第1項第4号',
      label: '工事を施工しない日または時間帯の定め',
      ok: t.nonWorkingDays.trim().length > 0,
      hint: '休工日や施工できない時間帯（稼働時間中など）を入力してください。',
    },
    {
      clause: '第19条第1項第5号',
      label: '前金払・出来形部分に対する支払の定め',
      ok: t.advancePayment.trim().length > 0,
      hint: '前金払・出来形払を行わない場合も「行わない」と明記が必要です。',
    },
    {
      clause: '第19条第1項第6号',
      label: '設計変更・工期変更等における変更・損害負担の定め',
      ok: hasTemplate,
      hint: '適用する約款テンプレートを選択すると、該当条項が自動で付帯します。',
    },
    {
      clause: '第19条第1項第7号',
      label: '天災その他不可抗力による工期変更・損害負担の定め',
      ok: hasTemplate,
      hint: '適用する約款テンプレートを選択すると、該当条項が自動で付帯します。',
    },
    {
      clause: '第19条第1項第8号',
      label: '価格等の変動に基づく請負代金・工事内容の変更',
      ok: hasTemplate,
      hint: '適用する約款テンプレートを選択すると、該当条項が自動で付帯します。',
    },
    {
      clause: '第19条第1項第9号',
      label: '第三者に与えた損害の賠償金の負担',
      ok: t.thirdPartyDamage.trim().length > 0,
      hint: '「契約条件」タブで第三者損害の負担区分を入力してください。',
    },
    {
      clause: '第19条第1項第10号',
      label: '支給材料・貸与機械の内容および方法',
      ok: t.suppliedMaterials.trim().length > 0,
      hint: '支給・貸与がない場合も「なし」と明記が必要です。',
    },
    {
      clause: '第19条第1項第11号',
      label: '完成検査の時期・方法および引渡しの時期',
      ok: Boolean(t.inspection.trim() && t.handover.trim()),
      hint: '検査の時期・方法と引渡し時期の両方を入力してください。',
    },
    {
      clause: '第19条第1項第12号',
      label: '完成後における請負代金の支払時期・方法',
      ok: t.paymentMethod.trim().length > 0,
      hint: '「契約条件」タブで支払時期と支払方法を入力してください。',
    },
    {
      clause: '第19条第1項第13号',
      label: '契約不適合責任（担保責任）または保証保険等の定め',
      ok: t.defectLiability.trim().length > 0,
      hint: '担保責任の期間・範囲を入力してください。',
    },
    {
      clause: '第19条第1項第14号',
      label: '履行遅滞・債務不履行の場合の遅延利息・違約金',
      ok: t.delayPenalty.trim().length > 0,
      hint: '遅延利息の年率など損害金の定めを入力してください。',
    },
    {
      clause: '第19条第1項第15号',
      label: '契約に関する紛争の解決方法',
      ok: t.disputeResolution.trim().length > 0,
      hint: '協議・あっせん・管轄裁判所など解決方法を入力してください。',
    },
    {
      clause: '第19条第1項第16号',
      label: 'その他国土交通省令で定める事項（当事者の商号・所在地等）',
      ok: Boolean(partner.name && partner.address && partner.tel),
      hint: '「取引先マスタ」で商号・所在地・連絡先を登録してください。',
    },
    {
      clause: '第20条第1項',
      label: '見積書における工事内容の内訳の明示',
      ok: project.items.length > 0 && project.items.every(i => i.name.trim().length > 0),
      hint: '見積明細に工種・仕様を記載してください。',
    },
  ];

  if (project.dealKind === 'order') {
    items.push({
      clause: '第40条の3ほか',
      label: '下請負人の建設業許可番号の確認・記録',
      ok: partner.licenseNo.trim().length > 0,
      hint: '「取引先マスタ」で協力会社の建設業許可番号を登録してください。',
    });
  }

  return items;
}

export function complianceSummary(items: ComplianceItem[]): { ok: number; total: number; rate: number } {
  const ok = items.filter(i => i.ok).length;
  const total = items.length;
  return { ok, total, rate: total === 0 ? 0 : Math.round((ok / total) * 100) };
}

export interface Article {
  no: string;
  title: string;
  body: string;
}

/** 契約条件から約款の条文を組み立てる（入力値が本文にそのまま反映される） */
export function buildArticles(project: Project, partner: Partner): Article[] {
  const t = project.terms;
  const totals = calcTotals(project.items, project.discount);
  const parties = partiesOf(project, partner);
  const na = (v: string, fallback: string) => (v.trim() ? v.trim() : fallback);
  const period =
    t.startDate && t.endDate
      ? `着手 ${formatDate(t.startDate)}、完成 ${formatDate(t.endDate)}`
      : '未定（契約条件に着手日・完成日を入力してください）';

  return [
    {
      no: '第1条',
      title: '総則',
      body: `${parties.orderer.name}（以下「甲」という。）と ${parties.contractor.name}（以下「乙」という。）は、${project.title} に関する工事請負契約について、本約款の定めるところにより誠実に履行する。`,
    },
    {
      no: '第2条',
      title: '工事内容',
      body: `工事名 ${project.title}／工事場所 ${project.site}／工事内容 ${project.scope}。詳細は見積書 ${documentNo(project, 'quote')} の明細による。`,
    },
    {
      no: '第3条',
      title: '請負代金の額',
      body: `請負代金の額は ${formatYen(totals.total)}（うち消費税額等 ${formatYen(totals.tax)}）とする。`,
    },
    {
      no: '第4条',
      title: '工期',
      body: `工期は ${period} とする。`,
    },
    {
      no: '第5条',
      title: '工事を施工しない日または時間帯',
      body: na(t.nonWorkingDays, '別途甲乙協議のうえ定める。'),
    },
    {
      no: '第6条',
      title: '前金払および出来形部分に対する支払',
      body: na(t.advancePayment, '別途甲乙協議のうえ定める。'),
    },
    {
      no: '第7条',
      title: '設計変更・工期の変更',
      body: '甲または乙の申出により設計変更、工事着手の延期または工事の中止が生じた場合、工期の変更、請負代金の額の変更および損害の負担は、甲乙協議のうえ書面により定める。',
    },
    {
      no: '第8条',
      title: '不可抗力による損害',
      body: '天災その他甲乙いずれの責にも帰することができない事由により工期の変更または損害が生じた場合、その負担および額の算定方法は甲乙協議のうえ定める。',
    },
    {
      no: '第9条',
      title: '価格等の変動',
      body: '資材価格、労務費その他の価格等に著しい変動が生じたときは、甲乙協議のうえ請負代金の額または工事内容を変更することができる。',
    },
    {
      no: '第10条',
      title: '第三者に与えた損害',
      body: na(t.thirdPartyDamage, '施工に起因して第三者に与えた損害の負担は甲乙協議のうえ定める。'),
    },
    {
      no: '第11条',
      title: '支給材料および貸与機械',
      body: na(t.suppliedMaterials, '支給材料・貸与機械の有無および方法は甲乙協議のうえ定める。'),
    },
    {
      no: '第12条',
      title: '完成検査および引渡し',
      body: `${na(t.inspection, '完成検査の時期および方法は甲乙協議のうえ定める。')} 引渡しは ${na(t.handover, '検査合格後、甲乙協議のうえ定める時期')} に行う。`,
    },
    {
      no: '第13条',
      title: '請負代金の支払',
      body: `${na(t.paymentMethod, '完成後の請負代金の支払時期および方法は甲乙協議のうえ定める。')} 支払条件は「${partner.paymentTerms}」による。`,
    },
    {
      no: '第14条',
      title: '契約不適合責任',
      body: `乙は、工事目的物に契約の内容に適合しない部分があるときは、${na(t.defectLiability, '引渡しの日から法令に定める期間')} その責任を負う。`,
    },
    {
      no: '第15条',
      title: '履行遅滞・違約金',
      body: na(t.delayPenalty, '履行遅滞その他債務不履行の場合の遅延利息および違約金は甲乙協議のうえ定める。'),
    },
    {
      no: '第16条',
      title: '紛争の解決',
      body: na(t.disputeResolution, '本契約に関する紛争は甲乙協議のうえ解決する。'),
    },
  ];
}
