// 工事契約書類管理システム — 型定義

/** 取引区分: 顧客から受注する案件か、協力会社へ発注する案件か */
export type DealKind = 'receive' | 'order';

export const DEAL_KIND_LABELS: Record<DealKind, string> = {
  receive: '受注案件',
  order: '発注案件',
};

/** 案件（＝書類セット1件）のステータス */
export type ProjectStatus = 'draft' | 'quoted' | 'ordered' | 'accepted' | 'completed';

export const PROJECT_STATUS_LABELS: Record<ProjectStatus, string> = {
  draft: '見積作成中',
  quoted: '見積提出済',
  ordered: '注文書手配済',
  accepted: '契約成立',
  completed: '工事完了',
};

/** 取引区分に応じた表示名（受注案件と発注案件で書類の向きが逆になるため） */
export function projectStatusLabel(status: ProjectStatus, dealKind: DealKind): string {
  if (status === 'ordered') return dealKind === 'order' ? '注文書送付済' : '注文書受領済';
  if (status === 'accepted') return dealKind === 'order' ? '発注確定' : '受注確定';
  return PROJECT_STATUS_LABELS[status];
}

export const PROJECT_STATUS_TONE: Record<ProjectStatus, string> = {
  draft: 'muted',
  quoted: 'info',
  ordered: 'warning',
  accepted: 'accent',
  completed: 'success',
};

export const PROJECT_STATUS_ORDER: ProjectStatus[] = ['draft', 'quoted', 'ordered', 'accepted', 'completed'];

/** 書類の種類（建設業法で一式管理が必要な4点） */
export type DocKind = 'quote' | 'order' | 'acceptance' | 'terms';

export const DOC_KIND_LABELS: Record<DocKind, string> = {
  quote: '見積書',
  order: '注文書',
  acceptance: '注文請書',
  terms: '基本契約書（約款）',
};

export const DOC_KIND_SHORT: Record<DocKind, string> = {
  quote: '見積',
  order: '注文',
  acceptance: '請書',
  terms: '約款',
};

export const DOC_KINDS: DocKind[] = ['quote', 'order', 'acceptance', 'terms'];

/** 各書類の進捗 */
export type DocStatus = 'none' | 'created' | 'sent' | 'sealed';

export const DOC_STATUS_LABELS: Record<DocStatus, string> = {
  none: '未作成',
  created: '作成済',
  sent: '送付済',
  sealed: '押印・締結済',
};

export interface DocumentRecord {
  kind: DocKind;
  /** 書類番号（例 EST-2026-0031）。未作成なら空 */
  no: string;
  status: DocStatus;
  /** 作成日 YYYY-MM-DD。未作成なら undefined */
  issuedOn?: string;
  /** 見積書から自動生成された書類かどうか */
  autoGenerated: boolean;
  /** 生成時点の見積改訂番号。見積を後から変更した場合の再生成判定に使う */
  sourceRevision?: number;
}

/** 見積明細 */
export interface QuoteItem {
  id: string;
  /** 工種・品名 */
  name: string;
  /** 仕様・規格 */
  spec: string;
  quantity: number;
  unit: string;
  unitPrice: number;
}

/** 取引先（発注者 / 協力会社） */
export type PartnerKind = 'client' | 'subcontractor';

export const PARTNER_KIND_LABELS: Record<PartnerKind, string> = {
  client: '発注者（得意先）',
  subcontractor: '協力会社（下請）',
};

export interface Partner {
  id: string;
  /** 会社名（架空。固有部分は 〇〇 で伏せる） */
  name: string;
  kind: PartnerKind;
  /** 部署 */
  department: string;
  /** 先方担当者名 */
  contactName: string;
  postalCode: string;
  address: string;
  tel: string;
  email: string;
  /** 建設業許可番号（協力会社のみ保持。未取得なら空） */
  licenseNo: string;
  /** 支払条件（書類へ自動反映） */
  paymentTerms: string;
  note: string;
}

/** 建設業法第19条第1項に基づく契約条件（注文書・約款へ自動反映） */
export interface ContractTerms {
  /** 着手時期 YYYY-MM-DD */
  startDate: string;
  /** 完成時期 YYYY-MM-DD */
  endDate: string;
  /** 施工しない日・時間帯の定め */
  nonWorkingDays: string;
  /** 前金払・出来形払の定め */
  advancePayment: string;
  /** 完成検査の時期・方法 */
  inspection: string;
  /** 引渡しの時期 */
  handover: string;
  /** 完成後の請負代金の支払時期・方法 */
  paymentMethod: string;
  /** 契約不適合責任（担保責任）の期間・内容 */
  defectLiability: string;
  /** 遅延利息・違約金 */
  delayPenalty: string;
  /** 第三者損害の賠償負担 */
  thirdPartyDamage: string;
  /** 支給材料・貸与機械の定め */
  suppliedMaterials: string;
  /** 紛争の解決方法 */
  disputeResolution: string;
  /** 適用する約款テンプレート */
  termsTemplateId: string;
}

export interface HistoryEntry {
  id: string;
  at: string;
  actorName: string;
  action: string;
}

export interface Project {
  id: string;
  /** 案件番号（例 KJ-2026-0031） */
  no: string;
  /** 工事名称 */
  title: string;
  dealKind: DealKind;
  status: ProjectStatus;
  /** 取引先ID（受注案件なら発注者、発注案件なら協力会社） */
  partnerId: string;
  /** 工事場所 */
  site: string;
  /** 工事内容の概要 */
  scope: string;
  /** 自社側の担当者 */
  staff: string;
  /** 見積提出日 YYYY-MM-DD */
  quotedOn: string;
  /** 見積有効期限 YYYY-MM-DD */
  quoteExpiry: string;
  items: QuoteItem[];
  /** 値引額（円） */
  discount: number;
  terms: ContractTerms;
  documents: DocumentRecord[];
  /** 見積の改訂番号。明細や条件を変更するたびに +1 する */
  revision: number;
  history: HistoryEntry[];
  updatedAt: string;
  /** 出力済みの書類一式ファイル名（未出力なら undefined） */
  bundleFileName?: string;
}

/** 建設業法チェック項目の判定結果 */
export interface ComplianceItem {
  /** 建設業法第19条第1項の号数など */
  clause: string;
  label: string;
  ok: boolean;
  /** 未充足時に何を入力すればよいか（日本語） */
  hint: string;
}
