// 工事契約書類管理システム — 型定義

/** 案件（＝書類セット1件）のステータス */
export type ProjectStatus = 'imported' | 'ordered' | 'accepted' | 'completed';

export const PROJECT_STATUS_LABELS: Record<ProjectStatus, string> = {
  imported: '見積書を取込済み',
  ordered: '注文書・約款を受領済み',
  accepted: '契約成立',
  completed: '工事完了',
};

export const PROJECT_STATUS_TONE: Record<ProjectStatus, string> = {
  imported: 'info',
  ordered: 'warning',
  accepted: 'accent',
  completed: 'success',
};

/** 業務の進み具合（画面上部のステップ表示用）。案件詳細の「次にやること」と1対1で対応する */
export const FLOW_STEPS: string[] = ['見積書の取り込み', '3つの書類を作る', '注文書・約款をもらう・請書を出す', '工事完了'];

/**
 * いまどのステップにいるかを返す。
 * 3書類を作ったかどうかで進み具合が変わるため、ステータスだけでは決まらない。
 * 全ステップ完了時は FLOW_STEPS.length を返す。
 */
export function flowStepIndex(status: ProjectStatus, generated: boolean): number {
  if (status === 'completed') return FLOW_STEPS.length;
  if (status === 'accepted') return 3;
  if (!generated) return 1;
  return 2;
}

/** 書類の種類（建設業法で一式管理が必要な4点） */
export type DocKind = 'quote' | 'order' | 'acceptance' | 'terms';

export const DOC_KIND_LABELS: Record<DocKind, string> = {
  quote: '見積書',
  order: '注文書',
  acceptance: '注文請書',
  terms: '基本契約書（約款）',
};

/** それぞれの書類が何のための紙なのかを、ひとことで説明する */
export const DOC_KIND_PLAIN: Record<DocKind, string> = {
  quote: 'いくらでお引き受けするかを示す書類',
  order: '工事を注文する側が出す書類',
  acceptance: '注文をお請けしたことを伝える書類',
  terms: '工期や支払いなどの約束ごとをまとめた書類',
};

export const DOC_KINDS: DocKind[] = ['quote', 'order', 'acceptance', 'terms'];

/** 各書類の進捗 */
export type DocStatus = 'none' | 'created' | 'sent' | 'sealed';

/** 注文書・注文請書・約款の状態表示。見積書だけは docStatusLabel() で呼び方を変える */
export const DOC_STATUS_LABELS: Record<DocStatus, string> = {
  none: '未作成',
  created: '作成済み',
  sent: '送付済み',
  sealed: '押印済み',
};

export interface DocumentRecord {
  kind: DocKind;
  /** 書類番号（例 EST-2026-0031）。未作成なら空 */
  no: string;
  status: DocStatus;
  /** 作成日 YYYY-MM-DD。未作成なら undefined */
  issuedOn?: string;
  /** 見積書から自動生成された書類かどうか */
  autoGenerated: boolean;
  /** 生成時点の見積改訂番号。見積書を差し替えた場合の再生成判定に使う */
  sourceRevision?: number;
}

/** 見積明細（取り込んだ見積書から読み取った内容。システム上は編集しない） */
export interface QuoteItem {
  id: string;
  /** 工種・品名 */
  name: string;
  /** 仕様・規格 */
  spec: string;
  quantity: number;
  unit: string;
  unitPrice: number;
}

/** 取引先（工事を注文するお客様） */
export interface Partner {
  id: string;
  /** 会社名（架空。固有部分は 〇〇 で伏せる） */
  name: string;
  /** 部署 */
  department: string;
  /** 先方担当者名 */
  contactName: string;
  postalCode: string;
  address: string;
  tel: string;
  /** 支払条件（書類へ自動反映） */
  paymentTerms: string;
}

/**
 * 案件ごとに決める工事の条件。
 * これ以外の法定記載事項（設計変更・不可抗力・検査・引渡し・遅延利息など）は
 * 約款テンプレートに定型条項として持たせ、担当者が入力する必要をなくしている。
 */
export interface ContractTerms {
  /** 着手時期 YYYY-MM-DD */
  startDate: string;
  /** 完成時期 YYYY-MM-DD */
  endDate: string;
  /** 工事ができない日・時間帯 */
  nonWorkingDays: string;
  /** 代金の支払時期・方法（取引先マスタから自動で入る） */
  paymentMethod: string;
}

export interface HistoryEntry {
  id: string;
  at: string;
  actorName: string;
  action: string;
}

/** 取り込み元の見積書ファイル */
export interface SourceFile {
  /** ファイル名（Excel で作成した見積書をそのまま取り込む想定） */
  name: string;
  /** 取込日時（ISO） */
  importedAt: string;
}

export interface Project {
  id: string;
  /** 案件番号（例 KJ-2026-0031） */
  no: string;
  /** 工事名称 */
  title: string;
  status: ProjectStatus;
  /** 取引先ID（工事を注文するお客様） */
  partnerId: string;
  /** 工事場所 */
  site: string;
  /** 工事内容の概要 */
  scope: string;
  /** 自社側の担当者 */
  staff: string;
  /** 見積書の日付 YYYY-MM-DD */
  quotedOn: string;
  /** 見積有効期限 YYYY-MM-DD */
  quoteExpiry: string;
  /** 取り込んだ見積書から読み取った明細 */
  items: QuoteItem[];
  /** 値引額（円。見積書に記載があれば読み取る） */
  discount: number;
  /** 取り込んだ見積書ファイル */
  sourceFile: SourceFile;
  terms: ContractTerms;
  documents: DocumentRecord[];
  /** 見積書の版。差し替えるたびに +1 する */
  revision: number;
  history: HistoryEntry[];
  updatedAt: string;
  /** 出力済みの書類一式ファイル名（未出力なら undefined） */
  bundleFileName?: string;
}

/** 書類に必要な項目のチェック結果 */
export interface ComplianceItem {
  /** 担当者に分かる言葉での項目名 */
  label: string;
  ok: boolean;
  /** 充足しているときに表示する内容 */
  value: string;
  /** 未充足時に何をすればよいか（日本語） */
  hint: string;
}

/** 取込待ちの見積書ファイル（共有フォルダに保存された Excel 見積書を想定） */
export interface QuoteFile {
  id: string;
  /** ファイル名 */
  name: string;
  /** 保存日時（ISO） */
  savedAt: string;
  /** 作成者（自社担当者） */
  savedBy: string;
  /** ファイルサイズ（KB） */
  sizeKb: number;
  /** 読み取り結果 */
  read: QuoteReadResult;
}

/** 見積書ファイルから読み取った内容 */
export interface QuoteReadResult {
  partnerId: string;
  title: string;
  site: string;
  scope: string;
  quotedOn: string;
  quoteExpiry: string;
  items: QuoteItem[];
  discount: number;
  /** 見積書に書かれていた工期（読み取れない場合は空） */
  startDate: string;
  endDate: string;
  /** 見積書に書かれていた「工事ができない日」（読み取れない場合は空） */
  nonWorkingDays: string;
}

/** ログインできる利用者（デモ用） */
export interface DemoAccount {
  loginId: string;
  password: string;
  name: string;
  department: string;
}

/** ログイン中の利用者 */
export type AppUser = Omit<DemoAccount, 'password'>;
